/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountCard: typeof import('./../components/business/account/AccountCard.vue')['default']
    ArticleEditor: typeof import('./../components/business/article/ArticleEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./../components/common/ErrorBoundary.vue')['default']
    LoadingButton: typeof import('./../components/common/button/LoadingButton.vue')['default']
    LoadingState: typeof import('./../components/common/LoadingState.vue')['default']
    PlatformIcon: typeof import('./../components/business/account/PlatformIcon.vue')['default']
    PlatformSelector: typeof import('./../components/business/publish/PlatformSelector.vue')['default']
    ProgressCard: typeof import('./../components/business/publish/ProgressCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
